POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
    "name": "Dave Prowse",
    "dateOfBirth": "1986-07-09",
    "ssn": "090786-122X",
    "gender": "numa",
    "occupation": "New york city cop"
}